# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    ex06.CreateTableService:
        class: ex06\Bundle\Service\CreateTableService
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
