<?php

namespace E05\Bundle\Repository;

/**
 * DislikesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DislikesRepository extends \Doctrine\ORM\EntityRepository
{
}
