# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    E01.RegisterService:
        class: E01\Bundle\Services\RegisterService
        arguments: ['@form.factory']
