# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    E01.RegisterService:
        class: E01\Bundle\Services\RegisterService
        arguments: ['@form.factory']

    E01.LoginService:
        class: E01\Bundle\Services\LoginService
        arguments: ['@form.factory']

    E04.SessionService:
        class: E04\Bundle\Services\SessionService
        #arguments: ['@form.factory']
