# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    ex08.TableService:
        class: ex08\Bundle\Service\TableService
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
