<?php

namespace ex12\Bundle\Repository;

/**
 * personsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class personsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Fetch persons with their related addresses and bank accounts,
     * optionally filtered by birthdate and sorted by name.
     *
     * @param \DateTime|null $birthdateFilter
     * @param string $sortOrder 'ASC' or 'DESC'
     *
     * @return array
     */
    public function findWithRelationsAndFilter(\DateTime $birthdateFilter = null, $sortField = 'name', $sortOrder = 'ASC')
    {
        $qb = $this->createQueryBuilder('p')
            ->leftJoin('p.addresses', 'a')
            ->addSelect('a')
            ->leftJoin('p.bank_accounts', 'b')
            ->addSelect('b');

        if ($birthdateFilter) {
            $qb->andWhere('p.birthdate >= :birthdate')
            ->setParameter('birthdate', $birthdateFilter);
        }

        $qb->orderBy('p.' . $sortField, $sortOrder);

        return $qb->getQuery()->getResult();
    }
}
