<?php

namespace ex09\Bundle\Repository;

/**
 * bank_accountsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class bank_accountsRepository extends \Doctrine\ORM\EntityRepository
{
}
