<?php

namespace ex09\Bundle\Repository;

/**
 * personsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class personsRepository extends \Doctrine\ORM\EntityRepository
{
}
