<?php

namespace ex10\Bundle\Repository;

/**
 * orm_itemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class orm_itemRepository extends \Doctrine\ORM\EntityRepository
{
}
